Fixing indexing issue on last bin of amp cuts
spice-herald/detanalysis pull request #21
Opened 2024-12-11 22:32 UTC by magsreed

2024-12-22 20:37 UTC, rkromani commented
@michrw could you verify that you and Maggie don't have conflicting versions of what needs to be done? I just don't want us in a situation where we're "fixing" it by just changing back and forth

2024-12-23 17:38 UTC, michrw requested changes
Yea, this change is too brute force! I had earlier encountered errors that required to me to change the value of `on_cut_bin` in the semiautocuts.py code. #17 is where this change is made. It seems like this change would sometimes change the which value of `on_cut_bin`, but would conflict with my changes. I suggest reviewing my changes more and confirming they don't fight each other all the time.

2024-12-31 18:56 UTC, magsreed commented
I don't entirely understand the conflict, what's the case or example where these two would be incompatible? Or what indexing case would this fail?

2025-01-04 06:12 UTC, michrw commented
You seem to be explicitly undoing the line here
`elif ('val_lower' in self.cut_pars): self.values_lower[on_cut_bin-1] `. This line was edited to prevent the OFamp cut from referencing cut parameters that fall outside the actual range of OFamp.

2025-01-10 01:47 UTC, closed without merging